version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - external

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-web.rule=Host(`app.local`)"
      - "traefik.http.routers.traefik-web.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

    extra_hosts:
      - "traefik.local:127.0.0.1"

    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:

networks:
  external:
    external: true
